name: Bug Report
description: Report a bug to help us improve.
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Describe the bug clearly and concisely.
      placeholder: "Example: Deleting a task removes the wrong item."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: What steps should we follow to reproduce the bug?
      placeholder: |
        1. Add a new task
        2. Click the delete button
        3. Observe that the wrong task is deleted
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low
        - Medium
        - Critical
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if applicable.
      placeholder: "Leave empty if not applicable."
    validations:
      required: false
